### ISSUE TITLE
关于原书链接

### ISSUE THREAD

**Issue by zchrissirhcz** [Celthi/effective-debugging-zh#1]
Hi, Celthi

感谢翻译，关注你的知乎一段时间了，也对调试相关技术感兴趣（日常用 LLDB).

尝试了按 "effective debugging" 找到一本作者为Diomidis Spinellis编写的同名书，但没找到 Michael Yan 为作者的那一本。

如果可以，希望能在翻译的同时，添加一些关于原书的信息，谢谢

**Comment by Celthi** [comment]
中文版 见https://github.com/Celthi/effective-debugging-zh/issues/20
