### ISSUE TITLE
有后续的更新计划吗？

### ISSUE THREAD

**Issue by DualHappiness** [Celthi/effective-debugging-zh#15]
网上找了一圈貌似没有找到原版，前面的章节看来都写得挺好的，但看后面都没更新了。
请问有后续的更新计划吗？
如果能够提供原版的话，也可以一起帮忙翻译

**Comment by Celthi** [comment]
会陆续更新

**Comment by Celthi** [comment]
见 https://github.com/Celthi/effective-debugging-zh/issues/20
