### ISSUE TITLE
你好，原始的英文版本有吗？

### ISSUE THREAD

**Issue by lfwin** [Celthi/effective-debugging-zh#19]
能放个英文链接吗？中英文对照阅读更好，毕竟有些英文词汇翻译过来还是感觉别扭。
非常感谢

**Comment by yanqi27** [comment]
Hi @lfwin
I talked to my friend @Celthi on this. I am going to publish the English version online soon. So please wait for a bit. I appreciate your patience.
-Michael

**Comment by Celthi** [comment]
中文版 见https://github.com/Celthi/effective-debugging-zh/issues/20
