### ISSUE TITLE
有英文版本吗

### ISSUE THREAD

**Issue by anty** [Celthi/effective-debugging-zh#20]

**Comment by Celthi** [comment]
本书中文版已经出版 https://private-user-images.githubusercontent.com/5187962/291749262-29b04963-5535-432c-b56f-8a2d5dbc2ec6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzQxOTYsIm5iZiI6MTcwMzAzMzg5NiwicGF0aCI6Ii81MTg3OTYyLzI5MTc0OTI2Mi0yOWIwNDk2My01NTM1LTQzMmMtYjU2Zi04YTJkNWRiYzJlYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDA1ODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVhODJhZDE4MzJiMTEyNDc3YjAwODk1ZDg1NTJjZTI0NzJiYWYyYzRjMjg3NmJlNmUxNDcyYWQ2ZDM0NTg3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.79qpEvlr2w_6-aJJA6ojmR2GX5iqueVLmmyTYBp11Vg
